project_id = "jxulfosxcpjtqsoerdgg"

[functions.match-cigar-band]
verify_jwt = false

[functions.get-weekly-pick]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.search-nearby-lounges]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false
